### PR TITLE
Update various Gems to address known security vulnerabilities

### PR DESCRIPTION
**Pull request by scttnlsn**

### CODE REVIEW

**Comment by scttnlsn** [comment]
@sapraaman I changed the branch but it looks like `develop` needs to be rebased against `master`

**Comment by sapraaman** [comment]
@scttnlsn thats probably because of license file checked in after so many checkins on develop, something like that, will take a look

**Comment by sapraaman** [comment]
@scttnlsn did that, now try

**Comment by scttnlsn** [comment]
@sapraaman I rebased the branch against `develop` and it looks good now

**Pull request merged**
